version: '3.3'

networks:
  test12:

services:
  db:
    container_name: db
    image: mysql:latest
    volumes:
      - ./db/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cripto_pass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - test12

#  php-fpm:
#    image: php:8.2-fpm
#    expose:
#      - 9000
#    links:
#      - mysql
#    volumes:
#      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
#    networks:
#      - test12

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - test12

volumes:
    db_data: {}
    wp-content: {}
